apiVersion: v1
kind: PersistentVolume
metadata:
  name: azlamp-nfs-pv
spec:
  capacity:
    storage: {{ .Values.nfsStorageCapacity }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfsHost }}
    path: {{ .Values.nfsExportPath }}
