apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azlamp-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.nfsStorageCapacity }}
