apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-byo
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.0.1.100
    path: "/drbd/data"
